#-----------------------------
# ベースイメージ
#-----------------------------
# CUDA 10.0 for Debian
FROM nvidia/cuda:10.0-cudnn7-devel

#-----------------------------
# 基本ライブラリのインストール
#-----------------------------
# インストール時のキー入力待ちをなくす環境変数
ENV DEBIAN_FRONTEND noninteractive

RUN set -x && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    python3-dev \
    python3-pip \
    sudo \
    git \
    wget \
    curl \
    bzip2 \
    make \
    libprotobuf-dev \
    protobuf-compiler \
    libgoogle-glog-dev \
    libboost-all-dev \
    libcaffe-cuda-dev \
    libhdf5-dev \
    libatlas-base-dev \
    libopencv-dev \
    # imageのサイズを小さくするためにキャッシュ削除
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install -U numpy opencv-python 

# cmake のインストール（replace cmake as old version has CUDA variable bugs）
RUN wget https://github.com/Kitware/CMake/releases/download/v3.16.0/cmake-3.16.0-Linux-x86_64.tar.gz && \
    tar xzf cmake-3.16.0-Linux-x86_64.tar.gz -C /opt && \
    rm cmake-3.16.0-Linux-x86_64.tar.gz

ENV PATH="/opt/cmake-3.16.0-Linux-x86_64/bin:${PATH}"

#-----------------------------
# 環境変数
#-----------------------------
ENV LC_ALL=C.UTF-8
ENV export LANG=C.UTF-8
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/
ENV PYTHONPATH=$PYTHONPATH:/usr/local/python

ARG USER_NAME=ubuntu
ARG USER_ID=1000
ARG GROUP_NAME=sudo
ENV HOME=/home/${USER_NAME}
ARG WORK_DIR=${HOME}/share/openpose_wrapper

#-----------------------------
# openpose のインストール
#-----------------------------
WORKDIR /openpose
RUN git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose.git .

WORKDIR /openpose/build
RUN cmake \
    -DBUILD_PYTHON=ON \
    -DDOWNLOAD_BODY_MPI_MODEL:Bool=ON \
    -DDOWNLOAD_BODY_COCO_MODEL:Bool=ON \
    -DDOWNLOAD_FACE_MODEL:Bool=ON \
    -DDOWNLOAD_HAND_MODEL:Bool=ON \
    ..
    
RUN make -j `nproc`

WORKDIR /openpose/build/python/openpose
RUN cp pyopenpose.cpython-36m-x86_64-linux-gnu.so /usr/local/lib/python3.6/dist-packages

WORKDIR /usr/local/lib/python3.6/dist-packages
RUN ln -s pyopenpose.cpython-36m-x86_64-linux-gnu.so pyopenpose

# ビルドした openpose を workdir にコピー
ADD /openpose ${WORK_DIR}/

#-----------------------------
# 追加ライブラリのインストール
#-----------------------------
RUN pip3 install -U flask
RUN pip3 install -U flask_cors
RUN pip3 install -U requests
RUN pip3 install -U gunicorn
RUN pip3 install -U pillow
RUN pip3 install -U tqdm

#-----------------------------
# ユーザーの追加
#-----------------------------
RUN useradd --create-home --uid ${USER_ID} --groups ${GROUP_NAME} --home-dir ${HOME} --shell /bin/bash ${USER_NAME}

# ディレクトリの所有権を設定： sudo グループの設定
RUN chown -R ${USER_NAME}:${GROUP_NAME} ${HOME}
RUN echo "${USER_NAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-user

# user に sudo 権限を付与
#RUN sudo gpasswd -a ${USER_NAME} sudo

# ディレクトリのアクセス権を設定：全アクセスを許可
RUN chmod 777 ${HOME}

# 指定ユーザーに切り替え
USER ${USER_NAME}

#-----------------------------
# コンテナ起動後の作業ディレクトリ
#-----------------------------
WORKDIR ${WORK_DIR}

#-----------------------------
# モデルのダウンロード
#-----------------------------
#RUN curl http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/body_25/pose_iter_584000.caffemodel -o pose_iter_584000.caffemodel
#RUN curl http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel -o pose_iter_440000.caffemodel
#RUN curl http://posefs1.perception.cs.cmu.edu/OpenPose/models/face/pose_iter_116000.caffemodel -o pose_iter_116000.caffemodel
#RUN curl http://posefs1.perception.cs.cmu.edu/OpenPose/models/hand/pose_iter_102000.caffemodel -o pose_iter_102000.caffemodel
#RUN curl http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/mpi/pose_iter_160000.caffemodel -o pose_iter_160000.caffemodel
#RUN cp pose_iter_584000.caffemodel openpose/models/pose/body_25/
#RUN cp pose_iter_440000.caffemodel openpose/models/pose/coco/
#RUN cp pose_iter_160000.caffemodel openpose/models/pose/mpi/
#RUN cp pose_iter_116000.caffemodel openpose/models/face/
#RUN cp pose_iter_102000.caffemodel openpose/models/hand/
