version: '2.3'

services:
    app:
        container_name: openpose_ubuntu_cpu_container
        image: openpose_ubuntu_cpu_image
        volumes:
            - ${PWD}:/openpose_wrapper
            - ${PWD}/openpose_cpu:/openpose_cpu
            - /etc/group:/etc/group:ro
            - /etc/passwd:/etc/passwd:ro
        build:
            context: .
            dockerfile: docker/Dockerfile_cpu
        ports:
            - "5011:5011"
        tty: true
        environment:
            TZ: "Asia/Tokyo"
            LC_ALL: C.UTF-8
            LANG: C.UTF-8
        command: bash -c "cd openpose_server && python3 app.py --host 0.0.0.0 --port 5010 --debug"
